### ISSUE TITLE
[BUG] Tool does not work in Foundry v12 & dnd4+

### ISSUE THREAD

**Issue by wlukamto** [daft-develop/mob-attack-tool#28]
Clicking on the tool does nothing. Console outputs the following:
foundry.js:655 Error: An error occurred while rendering MobAttackDialog 145. weaponData.system.damage.parts is not iterable
[Detected 1 package: mob-attack-tool(0.8.1)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.js:5795:13

I am not using midiqol as of now.

**Comment by daft-develop** [comment]
Hey, thank you for reporting the bug and providing the error message as well, it's greatly appreciated!

I haven't tested against dnd4.x.x yet, so I suspect, based on the error message, that they've changed something on how the weapon damage is structured internally. Most likely the new "Activities" feature has moved things around (https://github.com/foundryvtt/dnd5e/wiki/Activities) and that's broken the module's attempt to list out all the attack options for the selected creatures.

I would like to support dnd4.x.x in the future, but I don't have an estimated timeline yet.

**Comment by daft-develop** [comment]
Closing with 0.9.0 release, which now supports D&D 5e v4.2
